# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xuheng Duan
title: graduate student at University of Illinois at Urbana Champaign
email: xuhengduanwork@gmail.com
website: https://github.com/SpiceOwlf

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  SpiceOwlf
linkedin_username: xuheng-duan

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, my name is Xuheng Duan 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Database System
        link: github.com/SpiceOwlf/CS411_track1_proj
        link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/SpiceOwlf/CS411_track1_proj
        quote: >
          Academic Project, Jan 2021 – May 2021
        description: | 
          •	Developed a website that mimic the functionalities of Amazon.

          •	The major language being used is JavaScript. The website utilized react framework for frontend, express as backend, and a SQL database management system on Google Cloud Platform to manage the data.

          •	Used React Hooks and React Components to enhance the development, and make subparts reusable in the implementation.

          •	Designed a web crawler with Scrapy in Python that will pull GPU related data from internet.

      - layout: top-middle
        title: User Interface Design 

        quote: >
          Academic Project, Jan 2021 – May 2021
        description: | 
          •	Developed a visual appealing mobile phone app that achieved similar functionalities as Spotify from scratch.

          •	Experienced entire design lifecycle, which includes designing phase, user interview phase and implementation phase. 

          •	Used flutter as frontend, flask as backend and handle the saved files locally. The project used JavaScript majorly, as well as other common languages like HTML and CSS. 

      - layout: top-middle
        title: Software Engineering 

        quote: >
          Academic Project, Sep 2020 – Dec 2020

        description: | 
          •	Implemented multiple programing projects, which include developing Java web applications with bash scripts and Maven; building databases and using databases (SQL) in web applications; implementing different design patterns.
          
          •	Built Selenium test and JUnit test for the website, testing its functionality and edge cases.
          
          •	Utilized JSP for frontend and MariaDB as database.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Illinois at Urbana Champaign
        caption: 2020 - 2021
        sub_title: Master of Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.



  # - title: Education # Title for the section
    # layout: list # Type of content section (list/text)
    # content:
      - layout: left
        title: Boston College
        caption: 2016 - 2020
        sub_title: Bachelor of Science in Computer Science

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     # ![Trees](./images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
