# Site
repository: SpiceOwlf/SpiceOwlf.github.io
favicon: images/favicon.ico

version: 1

# Personal info
name: Xuheng Duan
title: Master of Computer Science at UIUC
email: xuhengduanwork@gmail.com

# Social links
# twitter_username: 
github_username:  spiceowlf
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: 
linkedin_username: xuheng-duan
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Hi, my name is Xuheng Duan. I am currently a CS graduate student at UIUC.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# # More Section
# more_title: When I'm Not Programming
# more_content: |
#     xxxxx
# # [jameswgrant](https://www.instagram.com/jameswgrant/).


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
